lesson 02 test 01 solved
js-tasks-ru/js-20200928_w-kunz pull request #2
Opened 2020-10-01 19:10 UTC by c0dewalker

2020-10-01 19:13 UTC, c0dewalker commented
lesson 02 test 01 solved

2020-10-01 19:18 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 02-javascript-data-types/1-sort-strings/index.spec.js — добавлен
```

2020-10-02 14:54 UTC, c0dewalker commented
Lesson 02 test 02 solved

2020-10-02 15:01 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-10-03 11:11 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return param === 'asc' ? sorted : sorted.reverse()
в этом решении есть несколько проблема - данные всегда сортируются по `asc` и только после этого происходит проверка `param === 'asc'` и в случае если она ложная, происходит `sorted.reverse()`

Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2020-10-03 11:14 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  for (let field of fields) {
подумайте в чем преимущества и недостатки решения с  итерации по `fields` по сравнению с итерацией по объекту `obj`. Ведь мы можем заменить `for...of` цикл по `fields` на обход свойств объекта

2020-10-03 11:14 UTC, dosandk requested changes
необходимо исправить задачу `sortStrings`

2020-10-04 12:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-04 12:43 UTC, c0dewalker commented on 02-javascript-data-types/2-pick/index.js
> +  for (let field of fields) {
Сделал теперь обоими вариантами, но пока к сожалению не вижу преимуществ или недостатков  отдельных способов. Было бы интересно узнать их. Спасибо.

2020-10-04 12:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-04 15:11 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  // const newObj = {}
не оставляйте закомментированный код в PR - это плохой тон

2020-10-04 15:12 UTC, dosandk approved these changes
good 👍

2020-10-04 15:12 UTC, merged